- id: atlantis-config-generate
  name: Atlantis config generate
  description: Generates atlantis.yaml config file based on the workspace directories
  entry:  pyke_hooks/atlantis-yaml-generate.py
  language: python
  types: [python]
- id: tfsort
  name: tfsort
  description: Run tfsort on all variables.tf and outputs.tf
  entry: pyke_hooks/tfsort.sh
  language: script
  files: (variables|outputs)\.tf$
  exclude: \.terraform\/.*$
